/**
 * Vendor the Bengali font from Google Fonts.
 *
 * We serve the font from our own origin instead of linking Google's CDN.
 * A course whose script stops rendering is worthless, and system Bengali
 * fonts vary enormously in conjunct coverage — several ship faces that
 * cannot shape the ligatures this course teaches.
 *
 * Google's own subsets already carry the OpenType layout features Bengali
 * needs (akhn, blwf, half, pstf, vatu, rphf), so we take their subset
 * rather than re-subsetting and risking dropping a feature.
 *
 *   node scripts/fetch-fonts.mjs
 */

import { writeFileSync, mkdirSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';

const SPEC = 'https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali:wght@400;500&display=swap';
const OUT = 'static/fonts';
// Google serves different subsets per UA; a modern desktop UA gets woff2.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const css = await (await fetch(SPEC, { headers: { 'User-Agent': UA } })).text();
mkdirSync(OUT, { recursive: true });

const faces = [];
for (const [, body] of css.matchAll(/@font-face\s*\{(.*?)\}/gs)) {
  const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
  const url = body.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  if (!range || !url) continue;
  // Keep only what the app renders: Bengali, and Latin for romanization.
  const kind = range.includes('U+0980') ? 'bengali' : range.includes('U+0000-00FF') ? 'latin' : null;
  if (!kind) continue;
  if (faces.some((f) => f.kind === kind)) continue; // variable font: one file serves all weights

  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  const name = `NotoSansBengali-${kind}-400.woff2`;
  writeFileSync(join(OUT, name), buf);
  faces.push({ kind, name, range, bytes: buf.length });
  console.log(`${name.padEnd(38)} ${String(buf.length).padStart(7)} bytes`);
}

// Drop anything left over from a previous run with different subsets.
for (const f of readdirSync(OUT)) {
  if (f.endsWith('.woff2') && !faces.some((x) => x.name === f)) {
    rmSync(join(OUT, f));
    console.log('removed stale', f);
  }
}

const header = `/*
 * Vendored Noto Sans Bengali — GENERATED by scripts/fetch-fonts.mjs.
 *
 * Served from our own origin so the course cannot break because a CDN
 * changed a subset or a device lacks a Bengali font. Google's subsets
 * preserve the OpenType layout features Bengali shaping needs; without
 * them conjuncts silently fall apart.
 *
 * unicode-range is kept per face so a Latin-only screen never pulls the
 * Bengali file. Weight is declared as a range because Noto Sans Bengali
 * is variable — one file serves 400 and 500.
 *
 * Regenerate: npm run fonts:fetch
 */`;

const blocks = faces.map(
  (f) => `@font-face {
  font-family: 'Noto Sans Bengali';
  font-style: normal;
  font-weight: 400 500;
  font-display: swap;
  src: url('/fonts/${f.name}') format('woff2');
  unicode-range: ${f.range};
}`
);

writeFileSync('src/fonts.css', [header, ...blocks].join('\n\n') + '\n');

const total = faces.reduce((n, f) => n + f.bytes, 0);
console.log(`\nwrote src/fonts.css — ${faces.length} faces, ${(total / 1024).toFixed(0)} KB total`);

const sums = faces.map((f) => createHash('md5').update(readFileSync(join(OUT, f.name))).digest('hex').slice(0, 8));
console.log('checksums:', sums.join(' '));
